In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

#Cleaning Non primed Data (use pickle in the future)

In [98]:
non_primed_survey = pd.read_csv("non-primed-q1.csv", encoding="ISO-8859-1")

In [99]:
non_primed_survey = non_primed_survey.iloc[1:,1:]

In [100]:
non_primed_survey

,Envisionÿ.1,Envisionÿ.2,Envisionÿ.3,Envisionÿ.4,Envisionÿ.5,Envisionÿ.6,Envisionÿ.7,Envisionÿ.8
1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,1,2,7,7,9,3.81,26
3,I believe my score is above average compared t...,2,4,12,5,3,3.12,26
4,Seeing an example high-scoring Envision projec...,3,3,4,12,4,3.42,26
5,When considering the possible levels of achiev...,1,1,4,8,12,4.12,26
6,I made my decisions based on previous work exp...,2,3,6,8,7,3.58,26
7,Iÿwill use Envision on future projects.,2,4,14,4,2,3.00,26
8,answered question,answered question,answered question,answered question,answered question,answered question,26,26
9,skipped question,skipped question,skipped question,skipped question,skipped question,skipped question,0,0

In [101]:
non_primed_survey.columns = non_primed_survey.iloc[0]

In [102]:
non_primed_survey = non_primed_survey.reindex(non_primed_survey.index.drop(1))

In [103]:
non_primed_survey

1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,1,2,7,7,9,3.81,26
3,I believe my score is above average compared t...,2,4,12,5,3,3.12,26
4,Seeing an example high-scoring Envision projec...,3,3,4,12,4,3.42,26
5,When considering the possible levels of achiev...,1,1,4,8,12,4.12,26
6,I made my decisions based on previous work exp...,2,3,6,8,7,3.58,26
7,Iÿwill use Envision on future projects.,2,4,14,4,2,3.00,26
8,answered question,answered question,answered question,answered question,answered question,answered question,26,26
9,skipped question,skipped question,skipped question,skipped question,skipped question,skipped question,0,0

In [104]:
non_primed_survey = non_primed_survey.iloc[:6,:]

In [105]:
non_primed_survey

1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,1,2,7,7,9,3.81,26
3,I believe my score is above average compared t...,2,4,12,5,3,3.12,26
4,Seeing an example high-scoring Envision projec...,3,3,4,12,4,3.42,26
5,When considering the possible levels of achiev...,1,1,4,8,12,4.12,26
6,I made my decisions based on previous work exp...,2,3,6,8,7,3.58,26
7,Iÿwill use Envision on future projects.,2,4,14,4,2,3.00,26

In [106]:
non_primed_survey.loc[7, 'Answer Options'] = "I will use Envision on future projects."

/Users/trippshealy/Documents/research/envision-role-model/.direnv/python-3.4.3/lib/python3.4/site-packages/pandas/core/indexing.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.4/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [107]:
non_primed_survey

1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,1,2,7,7,9,3.81,26
3,I believe my score is above average compared t...,2,4,12,5,3,3.12,26
4,Seeing an example high-scoring Envision projec...,3,3,4,12,4,3.42,26
5,When considering the possible levels of achiev...,1,1,4,8,12,4.12,26
6,I made my decisions based on previous work exp...,2,3,6,8,7,3.58,26
7,I will use Envision on future projects.,2,4,14,4,2,3.00,26

saved to pickle

In [111]:
primed_survey = pd.read_csv("primed-q1.csv", encoding="ISO-8859-1")

In [112]:
primed_survey

,Envision,Envision.1,Envision.2,Envision.3,Envision.4,Envision.5,Envision.6,Envision.7,Envision.8
0,Please Answer,Please Answer,Please Answer,Please Answer,Please Answer,Please Answer,Please Answer,Please Answer,Please Answer
1,Answer Options,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,I am confident a project team could really ach...,2,0,8,12,8,3.80,30
3,I believe the Envision score I came up with is...,I believe the Envision score I came up with is...,2,3,13,11,1,3.20,30
4,The Psomas Engineeringÿexample project motivat...,The Psomas Engineeringÿexample project motivat...,1,2,8,16,3,3.60,30
5,When considering the possible levels of achiev...,When considering the possible levels of achiev...,1,1,11,10,7,3.70,30
6,I made my decisions based on previous work exp...,I made my decisions based on previous work exp...,3,3,10,11,3,3.27,30
7,Iÿwill use Envision in the future.,Iÿwill use Envision in the future.,0,1,20,7,2,3.33,30
8,answered question,answered question,answered question,answered question,answered question,answered question,answered question,30,30
9,skipped question,skipped question,skipped question,skipped question,skipped question,skipped question,skipped question,0,0

In [113]:
primed_survey = primed_survey.iloc[1:,1:]

In [114]:
primed_survey

,Envision.1,Envision.2,Envision.3,Envision.4,Envision.5,Envision.6,Envision.7,Envision.8
1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,2,0,8,12,8,3.80,30
3,I believe the Envision score I came up with is...,2,3,13,11,1,3.20,30
4,The Psomas Engineeringÿexample project motivat...,1,2,8,16,3,3.60,30
5,When considering the possible levels of achiev...,1,1,11,10,7,3.70,30
6,I made my decisions based on previous work exp...,3,3,10,11,3,3.27,30
7,Iÿwill use Envision in the future.,0,1,20,7,2,3.33,30
8,answered question,answered question,answered question,answered question,answered question,answered question,30,30
9,skipped question,skipped question,skipped question,skipped question,skipped question,skipped question,0,0

In [115]:
primed_survey.columns = primed_survey.iloc[0]

In [116]:
primed_survey

1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,2,0,8,12,8,3.80,30
3,I believe the Envision score I came up with is...,2,3,13,11,1,3.20,30
4,The Psomas Engineeringÿexample project motivat...,1,2,8,16,3,3.60,30
5,When considering the possible levels of achiev...,1,1,11,10,7,3.70,30
6,I made my decisions based on previous work exp...,3,3,10,11,3,3.27,30
7,Iÿwill use Envision in the future.,0,1,20,7,2,3.33,30
8,answered question,answered question,answered question,answered question,answered question,answered question,30,30
9,skipped question,skipped question,skipped question,skipped question,skipped question,skipped question,0,0

In [117]:
primed_survey = primed_survey.reindex(primed_survey.index.drop(1))

In [118]:
primed_survey

1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,2,0,8,12,8,3.80,30
3,I believe the Envision score I came up with is...,2,3,13,11,1,3.20,30
4,The Psomas Engineeringÿexample project motivat...,1,2,8,16,3,3.60,30
5,When considering the possible levels of achiev...,1,1,11,10,7,3.70,30
6,I made my decisions based on previous work exp...,3,3,10,11,3,3.27,30
7,Iÿwill use Envision in the future.,0,1,20,7,2,3.33,30
8,answered question,answered question,answered question,answered question,answered question,answered question,30,30
9,skipped question,skipped question,skipped question,skipped question,skipped question,skipped question,0,0

In [119]:
primed_survey = primed_survey.iloc[:6,:]

In [120]:
primed_survey

1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,2,0,8,12,8,3.80,30
3,I believe the Envision score I came up with is...,2,3,13,11,1,3.20,30
4,The Psomas Engineeringÿexample project motivat...,1,2,8,16,3,3.60,30
5,When considering the possible levels of achiev...,1,1,11,10,7,3.70,30
6,I made my decisions based on previous work exp...,3,3,10,11,3,3.27,30
7,Iÿwill use Envision in the future.,0,1,20,7,2,3.33,30

In [126]:
primed_survey.loc[7, 'Answer Options'] = "I will use Envision on future projects."

/Users/trippshealy/Documents/research/envision-role-model/.direnv/python-3.4.3/lib/python3.4/site-packages/pandas/core/indexing.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/usr/local/lib/python3.4/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [127]:
primed_survey

1,Answer Options,Strongly Disagree (1),2,3,4,Strongly Agree (5),Rating Average,Response Count
2,I am confident a project team could really ach...,2,0,8,12,8,3.80,30
3,I believe the Envision score I came up with is...,2,3,13,11,1,3.20,30
4,The Psomas Engineeringÿexample project motivat...,1,2,8,16,3,3.60,30
5,When considering the possible levels of achiev...,1,1,11,10,7,3.70,30
6,I made my decisions based on previous work exp...,3,3,10,11,3,3.27,30
7,I will use Envision on future projects.,0,1,20,7,2,3.33,30

In [128]:
primed_survey.to_pickle("primed-q1.pickle")